export const ACTION_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    TOGGLE_CART_VISIBLE: "TOGGLE_CART_VISIBLE",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
    GET_COLLECTIONS_FROM_DB: "GET_COLLECTIONS_FROM_DB",
    GET_HOMEPAGE_SECTIONS_DB: "GET_HOMEPAGE_SECTIONS_DB",
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
    FETCH_SECTIONS_START: "FETCH_SECTIONS_START",
    FETCH_SECTIONS_SUCCESS: "FETCH_SECTIONS_SUCCESS",
    FETCH_SECTIONS_FAILURE: "FETCH_SECTIONS_FAILURE"
}