export const ACTION_TYPES = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    TOGGLE_CART_VISIBLE: "TOGGLE_CART_VISIBLE",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY"
}